package src.excecao;

import java.util.Scanner;

public class Finally {
	
	public static void main(String[] args) {
		System.out.println("Começo");
		
		Scanner entrada = new Scanner(System.in);
		try {
			System.out.println(7 / entrada.nextInt());
		} catch (Exception e) {
			System.out.println(e.getMessage());
		} finally {//um código que sempre é executado independente de ter erro ou não
			System.out.println("Finally #01...");
		}
	
		try {
			System.out.println(7 / entrada.nextInt());
		} finally {//um código que sempre é executado independente de ter erro ou não
			System.out.println("Finally #02...");
			entrada.close();
		}
		
		System.out.println("Fim:)");

	}
}
